name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Fixes"
    labels: ["bug", "fix"]
  - title: "🧰 Maintenance"
    labels: ["chore", "deps", "refactor", "docs"]
version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor", "feature"]
  patch:
    labels: ["patch", "fix", "chore", "deps"]
template: |
  ## Changes
  $CHANGES
