# .ruff.toml

line-length = 120
target-version = "py311"
extend-exclude = ["venv", "lists", "__pycache__"]

[lint]
# Keep correctness checks only for now.
select = ["E", "F"]
# Temporarily ignore long lines globally. We’ll tighten later.
ignore = ["E501"]

# Allow the early-draft bare `except:` patterns in timers.py only (for now).
per-file-ignores = { "timers.py" = ["E722"] }
