[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
# Keep the default rules; these two are the ones that bit us.
select = ["E", "F"]
# If you need to ignore something project-wide, add here:
ignore = []
