name: "🐛 Bug report"
description: Report a problem
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Clear description of the problem and expected behavior.
    validations: { required: true }
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) Run ...\n2) Use command ...\n3) See error ..."
  - type: input
    id: version
    attributes:
      label: Bot version / commit
      placeholder: "v0.1.0 or SHA"
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      render: shell
