name: "💡 Feature request"
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see and why?
    validations: { required: true }
  - type: textarea
    id: details
    attributes:
      label: Details / rough UX
      placeholder: "Slash command? Permissions? Config?"
