# nixpacks.toml

# Setup phase: install Python dependencies before any build or start
[phases.setup]
commands = ["pip install -r requirements.txt"]

# Start phase: launch the bot
[phases.start]
commands = ["python bot.py"]
