# gravity-list/nixpacks.toml

[phases.install]
# Use python -m pip so that we’re installing into the venv Nixpacks set up
commands = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.start]
commands = ["python bot.py"]
