# nixpacks.toml

# Install dependencies using venv's pip
[phases.install]
commands = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

# No build steps needed
[phases.build]
commands = []

# Start the bot
[phases.start]
commands = ["python bot.py"]
