[phases.install]
commands = [
  "echo \"Contents of /app:\" && ls -R /app",
  "echo \"Installing: $(cat requirements.txt)\"",
  "pip install -r requirements.txt"
]

[phases.start]
commands = ["python bot.py"]
