name: lint-test
on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      # Install runtime deps (optional, if you have requirements.txt)
      - name: Install app requirements
      - run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Install dev tools (Black, Ruff, pytest, pre-commit) from a pinned file
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (format check)
        run: black --check .

      # Optional: if/when you add tests
      # - name: Pytest
      #   run: pytest -q
