name: release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write   # needed to create/upload the release

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # so release notes can see prior tags/commits

      - name: Derive version from tag
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Make zipped distribution
        run: |
          mkdir -p dist
          NAME="Gravity-List-Bot-v${VERSION}"
          # zip everything except dev/ci-only bits
          zip -r "dist/${NAME}.zip" . \
            -x "*.git*" "venv/*" "__pycache__/*" "lists/*" ".github/*"
          sha256sum "dist/${NAME}.zip" > "dist/${NAME}.sha256"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          generate_release_notes: true
          files: |
            dist/*.zip
            dist/*.sha256
