name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write   # required to create a release & upload assets

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so the tag exists locally

      - name: Set up Python (for any light scripting if needed)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Build a source ZIP from the tagged commit, honoring .gitattributes export-ignore
      - name: Build source archive
        run: |
          set -euo pipefail
          echo "Tag: $GITHUB_REF_NAME"
          git archive --format=zip -o "Gravity-List-Bot-${GITHUB_REF_NAME}.zip" "$GITHUB_REF_NAME"
          sha256sum "Gravity-List-Bot-${GITHUB_REF_NAME}.zip" > "Gravity-List-Bot-${GITHUB_REF_NAME}.zip.sha256"
          ls -lh

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            Gravity-List-Bot-${{ github.ref_name }}.zip
            Gravity-List-Bot-${{ github.ref_name }}.zip.sha256
